version: "3.9"
services:
  timelapse:
    build: 
      context: .
      args:
        user: $USER
        tz: $TZ
    volumes:
      - type: bind
        source: ./videos
        target: /home/${USER}/videos
      - type: bind
        source: ./app
        target: /home/${USER}/app
      - type: bind
        source: ./crontab.example
        target: /var/spool/cron/crontabs/${USER}
    tmpfs:
      - /home/${USER}/stills:${uid},${gid}
      - /home/${USER}/assembly:${uid},${gid}
    networks:
      - timelapse
    restart: unless-stopped

  caddy:
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - type: bind
        source: ./videos
        target: /var/www/html
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - timelapse
    depends_on: 
      - php-fpm

  php-fpm:
    container_name: php-fpm
    image: php:7.4-fpm
    volumes:
      - type: bind
        source: ./videos
        target: /var/www/html
      - type: bind
        source: ./app/timelapse.conf
        target: /etc/timelapse/timelapse.conf
    networks:
      - timelapse
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  timelapse:
    name: timelapse
