version: "3.9"
services:

  timelapse:
    container_name: timelapse
    build:
      context: .
    environment:
      - PROJECTNAME=timelapse
      - FPS=30
      - RTSP_STREAM=rtsp://admin:PASSWORD@ip.add.r.ess:554/cam/url
    volumes:
      - type: bind
        source: /datapath
        target: /data
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
    restart: unless-stopped
